# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolutionsave',
            old_name='startingCoords',
            new_name='starting_coords',
        ),
    ]
