# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20160313_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpriteSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spritesJSON', models.CharField(max_length=68000)),
                ('colorsJSON', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='SpriteSetSave',
        ),
    ]
