# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20160313_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelsave',
            name='levelJSON',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='musicsave',
            name='notesJSON',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='musicsave',
            name='settingsJSON',
            field=models.CharField(max_length=100),
        ),
    ]
