# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20160313_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpriteSetSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spritesJSON', models.CharField(max_length=85000)),
                ('colorsJSON', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='spritesave',
            name='colorsJSON',
        ),
        migrations.RemoveField(
            model_name='spritesave',
            name='spritesJSON',
        ),
        migrations.AddField(
            model_name='spritesave',
            name='spriteJSON',
            field=models.CharField(default='null', max_length=1400),
            preserve_default=False,
        ),
    ]
