# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20160313_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spritesetsave',
            old_name='spritesJSON',
            new_name='spriteArrayJSON',
        ),
    ]
