# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20160313_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpriteObjectSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spritesDictionaryJSON', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='spritesetsave',
            name='spriteArrayJSON',
            field=models.CharField(max_length=4000),
        ),
    ]
