# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_auto_20160313_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spritesave',
            name='spriteJSON',
            field=models.CharField(max_length=1600),
        ),
    ]
