# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_auto_20160313_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicsave',
            name='settingsJSON',
            field=models.CharField(max_length=500),
        ),
    ]
