# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_auto_20160313_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spriteobjectsave',
            name='spritesDictionaryJSON',
            field=models.CharField(max_length=200),
        ),
    ]
